name: Build and Test

on: [push]

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 16.8.0
      - run: |
          npm i
      
      - name: Test
      - run: |
          npm run test
