name: TestWorkflow

on:
  workflow_dispatch:
    inputs:
      signBinaries:
        type: boolean
        description: sign
        default: false
      publishContainers:
        type: boolean
        description: publish
        default: false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest  
    steps:
    - name: build
      run: |
        echo "BUILD JOB"

  sign:
    name: sign
    if: github.event.inputs.signBinaries == 'true' )
    needs: build    
    runs-on: ubuntu-latest
    steps:

    - name: sign
      run: |
        echo "SIGN JOB"

  publish:
    name: publish
    runs-on: [ ubuntu-latest ]
    needs: [ build, sign ]
    steps:
    - name: publish
      run: |
        echo "PUBLISH JOB"

  deploy:
    name: deploy
    runs-on: [ ubuntu-latest ]
    if: github.event.inputs.publishContainers == 'true'
    needs: [ publish ]
    steps:
    - name: deploy
      run: |
        echo "DEPLOY JOB"

  sync:
    name: sync
    if: github.event.inputs.publishContainers == 'true'
    needs: [ publish ]
    runs-on: [ ubuntu-latest ]
    steps:
    - name: sync
      run: |
        echo "SYNC JOB"
